### ISSUE TITLE
Tippfehler

### ISSUE THREAD

**Issue by maximilianstefanac** [DennisSchulmeister/dhbwka-wwi-webprog-folien#1]
https://github.com/DennisSchulmeister/dhbwka-wwi-webprog-folien/blob/884cfcdf1a07f8e9f2fcabc0ba048bb1b89f53e4/static/4-server/servlets/index.html#L512

Java Enterpride Editon müsste Java Enterprise Edition heißen

**Comment by DennisSchulmeister** [comment]
Github sollte einem eine Mail schicken, wenn ein Issue angelegt wird. :) Danke für den Hinweis. Ich korrigiere es gleich.
